# Generated by Django 2.2.4 on 2019-09-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetail',
            name='unit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
